// <auto-generated />
using Discount.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.Grpc.Migrations
{
    [DbContext(typeof(DiscountContext))]
    [Migration("20241124063631_Initials")]
    partial class Initials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Discount.Grpc.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 750,
                            Description = "Xmas Bonus",
                            ProductName = "Fanta"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 750,
                            Description = "Xmas Bonus",
                            ProductName = "Sprite"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 750,
                            Description = "Xmas Bonus",
                            ProductName = "NutriYo"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1500,
                            Description = "Xmas Bonus",
                            ProductName = "Gulder Lager Beer"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1500,
                            Description = "Xmas Bonus",
                            ProductName = "Star Lager Beer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
