services:
  cataloguedb:
    image: postgres

  cartdb:
    image: postgres

  catalogueapi:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue/CatalogueApi/Dockerfile

volumes:
  postgres_catalogue:
  postgres_cart:

