services:
  cataloguedb:
    image: postgres

  cartdb:
    image: postgres

  distributedcache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  
  authenticationdb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  messagebroker:
    image: rabbitmq:management

  catalogueapi:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue/CatalogueApi/Dockerfile

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: Services/Cart/Cart.Api/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discounts/Discount.Grpc/Dockerfile

  odering.api:
    image: ${DOCKER_REGISTRY-}oderingapi
    build:
      context: .
      dockerfile: Services/Odering/Odering.Api/Dockerfile

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

  authentication.api:
    image: ${DOCKER_REGISTRY-}authenticationapi
    build:
      context: .
      dockerfile: Services/Auth_API/Authentication.API/Dockerfile

volumes:
  postgres_catalogue:
  postgres_cart:
  mssql_order:






